### ISSUE TITLE
Unlimited Nitro doesn't show the Nitro's smoke. (Suggestion)

### ISSUE THREAD

**Issue by GamerTroxynYT** [user-grinch/Cheat-Menu#19] opened 2019-12-04 01:28 UTC
I turn on Unlimited Nitro, but when I press the Nitro Button, it just make a shaking effect with screen. So you can't know if is changing something in the speed. It would be more beautiful to the mod if the nitro's effects appears. I'm talking about that Nitro's smoke.

**Comment by user-grinch** [comment] 2019-12-04 09:23
I've just pushed an update for it. Can you check if your issue is fixed or not?

**Comment by JorgeTebruski** [comment] 2019-12-04 15:12
When you enable this option, the menu is crashing. It is not reloading, even with the auto reload option enabled.

`[11:18:08.392335] (error)	Cheat Menu: opcode '06E7' call caused an unhandled exception
stack traceback:
	[C]: in function 'addVehicleMod'
	...an Andreas\moonloader\lib\cheat-menu\modules\vehicle.lua:389: in function 'AddComponentToVehicle'
	...an Andreas\moonloader\lib\cheat-menu\modules\vehicle.lua:245: in function <...an Andreas\moonloader\lib\cheat-menu\modules\vehicle.lua:241>
[11:18:08.412334] (error)	Cheat Menu: Script died due to an error. (id:1)
[11:18:29.173509] (system)	Unloading...
[11:18:30.200427] (system)	Session terminated.
`

**Comment by GamerTroxynYT** [comment] 2019-12-04 17:36
Yeah, now it's crashing, also when you leave a car, the same thing happens,

**Comment by user-grinch** [comment] 2019-12-04 18:07
Thanks for the report, I've found the issue and working on a fix asap.

**Comment by user-grinch** [comment] 2019-12-04 18:27
I just pushed an [update](https://github.com/user-grinch/Cheat-Menu/commit/7d5087a5cf51823a934c8ff09a8bdbf608048743). It should fix the issue.
Can you verify @JorgeTebruski ?

**Comment by JorgeTebruski** [comment] 2019-12-04 21:35
Now works perfectly, however, in the taxi does not work. He has time to recharge.

**Comment by user-grinch** [comment] 2019-12-05 08:46
I've tested the taxi and seems to work. Can you explain in detail what's happening?

**Comment by GamerTroxynYT** [comment] 2019-12-05 18:40
> I've tested the taxi and seems to work. Can you explain in detail what's happening?

For me is working perfectly

**Comment by JorgeTebruski** [comment] 2019-12-05 21:27
In my save game, the taxi missions are complete, so the taxis already have nitro. By activating the infinite nitro option, the taxi will not work.

There is a way to reproduce this without doing taxi missions, but it will affect all vehicles.

![nitro](https://user-images.githubusercontent.com/38569298/70275313-ab98ce80-178c-11ea-929f-6da0cc50e773.png)

**Comment by GamerTroxynYT** [comment] 2019-12-06 06:02
> In my save game, the taxi missions are complete, so the taxis already have nitro. By activating the infinite nitro option, the taxi will not work.
> 
> There is a way to reproduce this without doing taxi missions, but it will affect all vehicles.
> 
> ![nitro](https://user-images.githubusercontent.com/38569298/70275313-ab98ce80-178c-11ea-929f-6da0cc50e773.png)
> 
> Note that when nitro smoke exits, it cannot be activated until it disappears.

Seems like Grinch has to do that little improvement on that. It's a minimum detail, but still like a bug.

**Comment by user-grinch** [comment] 2019-12-06 06:23
Couldn't reproduce the issue but I'll do some more tests.

**Comment by JorgeTebruski** [comment] 2019-12-06 14:49
I thought it was better to record a video.

https://youtu.be/WgrTPI0Pd5g

**Comment by user-grinch** [comment] 2019-12-06 18:21
> I thought it was better to record a video.
> 
> https://youtu.be/WgrTPI0Pd5g

That helped. I'll take a look at it tomorrow.

**Comment by user-grinch** [comment] 2019-12-07 09:28
So there wasn't a proper solution to this. So I both car and taxi nitro cheats will be disabled while the unlimited nitro cheat is turned on. They can be turned on only if the unlimited nitro cheat is off.

**Comment by user-grinch** [comment] 2019-12-07 09:41
I've pushed the update on the master. Let me know if it works.

**Comment by JorgeTebruski** [comment] 2019-12-07 17:16
Tested and working as expected.

**Comment by user-grinch** [comment] 2019-12-08 04:17
Closing this as the issue got resolved.

**Closed by user-grinch** 2019-12-08 04:17 UTC
Labels: bug
